// data.ts
import type { DataType } from '../types/types';

const data: DataType = {
 // data.ts

main: [
  {
    title: "India Is Switching Gears",
    subheading:
      "Narendra Modi is propelling India toward new global influence with economic reforms and strategic foreign policies.",
    description:
      "India is redefining its role on the world stage. With bold initiatives, Modi is fostering innovation, enhancing infrastructure, and promoting diplomatic assertiveness.",
    image:
      "https://th-i.thgim.com/public/incoming/s4li5m/article65901826.ece/alternates/LANDSCAPE_1200/PTI09_10_2022_000168A.jpg",
  },
  {
    title: "Vibrant Democracy in Action",
    subheading:
      "PM Modi addresses the nation during a historic rally emphasizing development and unity.",
    description: "The speech highlights key reforms and people-driven governance.",
    image:
      "https://timesofindia.indiatimes.com/photo/msid-122148607/122148607.jpg?resizemode=4",
  },
  {
    title: "Global Diplomacy Leader",
    subheading: "Narendra Modi with world leaders at G20, representing India's global power.",
    description: "India asserts its presence on international forums.",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRHQYqsgM3v2ZV-Cp1hxqdi7eY5aJ-HLC4pFQ&s",
  },
  {
    title: "Transforming Bharat",
    subheading:
      "PM Modi's strategic roadmap for India@2047 gets global recognition.",
    description: "From economy to defense, India's rise is being acknowledged.",
    image:
      "https://akm-img-a-in.tosshub.com/indiatoday/images/story/202306/cover-story-lead-modi-sixteen_nine.jpg?VersionId=t9ufqQQkSundbGO_F8fdMcMEYucEznmz&size=690:388",
  },
]
,
  left: [
    {
      title: "The Non-Exoneration of Diddy",
      subheading:
        "New video surfaces, but critics say it raises more questions about the rapper’s actions than it answers. The debate intensifies in public and legal circles.",
      description: "Diddy faces renewed scrutiny despite video release.",
      author: "HELEN LEWIS",
      image:
        "https://cdn.theatlantic.com/thumbor/JYafOsnnpviegnswfQWafQ9M7ZI=/0x0:2000x1125/1952x1098/media/img/mt/2025/07/2025_07_diddy_2/original.jpg",
    },
    {
      title: "The AI Birthday Letter That Blew Me Away",
      subheading:
        "A heartfelt letter generated by ChatGPT stirs deep emotions in a family gathering, showing the unexpected depth of today’s artificial intelligence.",
      description: "AI-generated letter stuns family at birthday dinner.",
      author: "INDIA TECH",
      image:
        "https://images.unsplash.com/photo-1546422904-90eab23c3d7e?q=80&w=1172&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    },
  ],
  right: [
    {
      title: "What Trump—And the U.S.—Can’t Understand About Air Strikes",
      subheading:
        "Misinterpretation of air warfare strategy continues to hinder global trust in U.S. defense policy, especially under Trump’s rhetoric.",
      description: "Air strike logic misses critical strategic goals.",
      author: "PHILLIPS PAYSON O’BRIEN",
      image:
        "https://images.unsplash.com/photo-1546422904-90eab23c3d7e?q=80&w=1172&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    },
    {
      title: "The ‘Dirty and Nasty People’ Who Became Americans",
      subheading:
        "An eye-opening account of how early immigrants were ridiculed and dismissed, only to become key contributors to American identity and culture.",
      description: "Immigrant struggle forged modern America.",
      author: "LINDSAY CHERVINSKY",
      image:
        "https://images.unsplash.com/photo-1546422904-90eab23c3d7e?q=80&w=1172&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    },
  ],
  articles: new Array(12).fill(0).map((_, i) => ({
    title: `Top Article ${i + 1}`,
    subheading: `This feature explores the timely issues and stories shaping Article ${i + 1} — a reflective and informative dive into emerging perspectives.`,
    description: `An insightful look into topic ${i + 1}, highlighting fresh angles and ideas.`,
    image:
      "https://cdn.theatlantic.com/thumbor/yKqzBPUABWfbouMpUCKSX6Qg7oE=/0x0:4000x2250/1952x1098/media/img/mt/2025/07/2025_06_BBBHouse/original.jpg",
  })),
  latest: [
    {
      title: "Breaking: Modi Announces New AI Policy",
      subheading:
        "India aims to control its digital destiny with a framework focusing on ethical AI, local innovation, and global leadership.",
      description: "Modi's AI roadmap signals tech sovereignty push.",
      image:
        "https://images.unsplash.com/photo-1593789198777-f29bc259780e?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    },
    {
      title: "India Launches SpaceX-Style Rocket",
      subheading:
        "A landmark for India’s private aerospace sector, the launch reflects the government's effort to compete globally in space innovation.",
      description: "Private spaceflight reaches liftoff in India.",
      image:
        "https://cdn.theatlantic.com/thumbor/BCVBAJLrN_oZnewE0xj9n8-kWoc=/0x0:2160x2700/960x1200/media/img/2025/07/02/2025_07_02_Fireworks2_mpg/original.jpg",
    },
  ],
  mostRead: [
    {
      title: "The Rise of Indian Silicon Valley",
      subheading:
        "Bengaluru’s startup ecosystem is booming with VC investment, innovation hubs, and policy support. Could this surpass Silicon Valley?",
      description: "Bengaluru is becoming the tech capital of Asia.",
      image:
        "https://cdn.theatlantic.com/thumbor/BCVBAJLrN_oZnewE0xj9n8-kWoc=/0x0:2160x2700/960x1200/media/img/2025/07/02/2025_07_02_Fireworks2_mpg/original.jpg",
    },
    {
      title: "Inside Modi’s Vision for 2047",
      subheading:
        "India’s centennial will mark a powerful turning point if Modi’s long-term economic, social, and defense goals are achieved.",
      description: "India prepares for its next 100 years under vision 2047.",
      image:
        "https://images.unsplash.com/photo-1593789198777-f29bc259780e?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    },
  ],
};

export default data;
