// data.ts
import type { DataType } from '../types/types';

const data: DataType = {
 // data.ts

main: [
  {
    title: "India Is Switching Gears",
    subheading:
      "Narendra Modi is propelling India toward new global influence with economic reforms and strategic foreign policies.",
    description:
      "India is redefining its role on the world stage. With bold initiatives, Modi is fostering innovation, enhancing infrastructure, and promoting diplomatic assertiveness.",
    image:
      "https://th-i.thgim.com/public/incoming/s4li5m/article65901826.ece/alternates/LANDSCAPE_1200/PTI09_10_2022_000168A.jpg",
  },
  {
    title: "Vibrant Democracy in Action",
    subheading:
      "PM Modi addresses the nation during a historic rally emphasizing development and unity.",
    description: "The speech highlights key reforms and people-driven governance.",
    image:
      "https://timesofindia.indiatimes.com/photo/msid-122148607/122148607.jpg?resizemode=4",
  },
  {
    title: "Global Diplomacy Leader",
    subheading: "Narendra Modi with world leaders at G20, representing India's global power.",
    description: "India asserts its presence on international forums.",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRHQYqsgM3v2ZV-Cp1hxqdi7eY5aJ-HLC4pFQ&s",
  },
  {
    title: "Transforming Bharat",
    subheading:
      "PM Modi's strategic roadmap for India@2047 gets global recognition.",
    description: "From economy to defense, India's rise is being acknowledged.",
    image:
      "https://akm-img-a-in.tosshub.com/indiatoday/images/story/202306/cover-story-lead-modi-sixteen_nine.jpg?VersionId=t9ufqQQkSundbGO_F8fdMcMEYucEznmz&size=690:388",
  },
]
,
  left: [
    {
      title: "The Non-Exoneration of Diddy",
      subheading:
        "New video surfaces, but critics say it raises more questions about the rapper’s actions than it answers. The debate intensifies in public and legal circles.",
      description: "Diddy faces renewed scrutiny despite video release.",
      author: "HELEN LEWIS",
      image:
        "https://cdn.theatlantic.com/thumbor/JYafOsnnpviegnswfQWafQ9M7ZI=/0x0:2000x1125/1952x1098/media/img/mt/2025/07/2025_07_diddy_2/original.jpg",
    },
    {
      title: "The AI Birthday Letter That Blew Me Away",
      subheading:
        "A heartfelt letter generated by ChatGPT stirs deep emotions in a family gathering, showing the unexpected depth of today’s artificial intelligence.",
      description: "AI-generated letter stuns family at birthday dinner.",
      author: "INDIA TECH",
      image:
        "https://images.unsplash.com/photo-1546422904-90eab23c3d7e?q=80&w=1172&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    },
  ],
  right: [
    {
      title: "What Trump—And the U.S.—Can’t Understand About Air Strikes",
      subheading:
        "Misinterpretation of air warfare strategy continues to hinder global trust in U.S. defense policy, especially under Trump’s rhetoric.",
      description: "Air strike logic misses critical strategic goals.",
      author: "PHILLIPS PAYSON O’BRIEN",
      image:
        "https://images.unsplash.com/photo-1546422904-90eab23c3d7e?q=80&w=1172&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    },
    {
      title: "The ‘Dirty and Nasty People’ Who Became Americans",
      subheading:
        "An eye-opening account of how early immigrants were ridiculed and dismissed, only to become key contributors to American identity and culture.",
      description: "Immigrant struggle forged modern America.",
      author: "LINDSAY CHERVINSKY",
      image:
        "https://images.unsplash.com/photo-1546422904-90eab23c3d7e?q=80&w=1172&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    },
  ],
articles: [
  {
    title: "How India's Villages Are Powering a Green Future",
    subheading:
      "Rural India is emerging as a surprise leader in renewable energy adoption, setting examples in community-led solar innovation, biomass utilization, and off-grid power independence.",
    description:
      "With small-scale solar plants and bio-energy systems, India’s villages are pushing the boundaries of what grassroots sustainability can look like, drawing global attention to rural-led energy transformation.",
    image:
      "https://cdn.theatlantic.com/thumbor/yKqzBPUABWfbouMpUCKSX6Qg7oE=/0x0:4000x2250/1952x1098/media/img/mt/2025/07/2025_06_BBBHouse/original.jpg",
  },
  {
    title: "The Quiet Revolution in India’s Startup Ecosystem",
    subheading:
      "Beyond Bengaluru and Mumbai, Tier-2 cities are spawning a wave of ambitious startups, rewriting the rules of innovation and tech development in India.",
    description:
      "Fuelled by digital penetration and government-backed incubators, cities like Indore, Surat, and Kochi are now on the global startup radar — and they’re just getting started.",
    image:
      "https://cdn.theatlantic.com/thumbor/yKqzBPUABWfbouMpUCKSX6Qg7oE=/0x0:4000x2250/1952x1098/media/img/mt/2025/07/2025_06_BBBHouse/original.jpg",
  },
  {
    title: "Why India’s Youth Are Redefining Political Activism",
    subheading:
      "A new wave of politically engaged youth is using social media, grassroots organizing, and campus movements to challenge the status quo — and they’re being heard.",
    description:
      "From climate marches to digital protests, Gen Z Indians are demanding accountability and representation in unprecedented ways, reshaping India’s political landscape.",
    image:
      "https://cdn.theatlantic.com/thumbor/yKqzBPUABWfbouMpUCKSX6Qg7oE=/0x0:4000x2250/1952x1098/media/img/mt/2025/07/2025_06_BBBHouse/original.jpg",
  },
  {
    title: "Inside the Mission to Make India a Semiconductor Hub",
    subheading:
      "As global supply chains shift, India is making a bold play to become a semiconductor manufacturing powerhouse, with multi-billion dollar investments and policy backing.",
    description:
      "With strategic MoUs and support from nations like Japan and the U.S., India’s chip dream could transform its tech and defense sectors in the next decade.",
    image:
      "https://cdn.theatlantic.com/thumbor/yKqzBPUABWfbouMpUCKSX6Qg7oE=/0x0:4000x2250/1952x1098/media/img/mt/2025/07/2025_06_BBBHouse/original.jpg",
  },
  {
    title: "Can India Lead the Global South?",
    subheading:
      "Amid shifting geopolitical tides, India is increasingly positioning itself as the voice of the Global South — but does it have the influence and resources to lead?",
    description:
      "India’s G20 presidency, its strong partnerships with Africa, and non-alignment legacy offer both opportunity and challenge in steering a coalition of emerging economies.",
    image:
      "https://cdn.theatlantic.com/thumbor/yKqzBPUABWfbouMpUCKSX6Qg7oE=/0x0:4000x2250/1952x1098/media/img/mt/2025/07/2025_06_BBBHouse/original.jpg",
  },
  {
    title: "The Race to Digitize India’s Education System",
    subheading:
      "EdTech giants, public institutions, and grassroots innovators are converging in a nationwide push to overhaul outdated education systems with new-age digital tools.",
    description:
      "Despite infrastructure gaps, India is witnessing a surge in personalized learning, regional language platforms, and AI-enabled tutoring — reshaping how 300 million students learn.",
    image:
      "https://cdn.theatlantic.com/thumbor/yKqzBPUABWfbouMpUCKSX6Qg7oE=/0x0:4000x2250/1952x1098/media/img/mt/2025/07/2025_06_BBBHouse/original.jpg",
  },
  {
    title: "Reclaiming Indian History: The Archive Movement",
    subheading:
      "Digital historians and citizen archivists are leading a movement to preserve, digitize, and reinterpret India’s colonial, tribal, and regional narratives.",
    description:
      "In an age of misinformation and revisionism, the fight for preserving India’s diverse history has found new allies in open-source tech and crowdsourced archiving.",
    image:
      "https://cdn.theatlantic.com/thumbor/yKqzBPUABWfbouMpUCKSX6Qg7oE=/0x0:4000x2250/1952x1098/media/img/mt/2025/07/2025_06_BBBHouse/original.jpg",
  },
  {
    title: "India’s Climate Strategy: Adapt, Innovate, Lead",
    subheading:
      "From hydrogen hubs to net-zero villages, India’s climate efforts are shifting from reactive disaster response to proactive global leadership.",
    description:
      "With rising temperatures and resource stress, India’s approach blends traditional wisdom with cutting-edge clean technologies, redefining what climate resilience looks like.",
    image:
      "https://cdn.theatlantic.com/thumbor/yKqzBPUABWfbouMpUCKSX6Qg7oE=/0x0:4000x2250/1952x1098/media/img/mt/2025/07/2025_06_BBBHouse/original.jpg",
  },
  {
    title: "What the World Can Learn From India's UPI Boom",
    subheading:
      "The Unified Payments Interface has turned India into a fintech laboratory, setting benchmarks for the world on real-time payments and digital inclusion.",
    description:
      "India's cashless revolution is rewriting financial norms — from kirana stores to metro cities — offering a blueprint for digital public infrastructure globally.",
    image:
      "https://cdn.theatlantic.com/thumbor/yKqzBPUABWfbouMpUCKSX6Qg7oE=/0x0:4000x2250/1952x1098/media/img/mt/2025/07/2025_06_BBBHouse/original.jpg",
  },
  {
    title: "How India Is Tackling the Mental Health Crisis",
    subheading:
      "With rising awareness, community-led helplines, and tech-driven therapy, India is breaking taboos around mental health — but challenges remain.",
    description:
      "Amid a surge in cases post-COVID, mental health in India is no longer a fringe issue. Policy, media, and youth activism are rewriting the narrative.",
    image:
      "https://cdn.theatlantic.com/thumbor/yKqzBPUABWfbouMpUCKSX6Qg7oE=/0x0:4000x2250/1952x1098/media/img/mt/2025/07/2025_06_BBBHouse/original.jpg",
  },
  {
    title: "Is India Ready for the AI Age?",
    subheading:
      "The country is witnessing an AI gold rush — but balancing regulation, innovation, and ethics is a tightrope act with huge consequences.",
    description:
      "With the rise of deepfakes, job displacement concerns, and homegrown LLMs, India stands at a critical junction in how it embraces artificial intelligence.",
    image:
      "https://cdn.theatlantic.com/thumbor/yKqzBPUABWfbouMpUCKSX6Qg7oE=/0x0:4000x2250/1952x1098/media/img/mt/2025/07/2025_06_BBBHouse/original.jpg",
  },
  {
    title: "The Women Driving India’s Space Program",
    subheading:
      "Behind every ISRO mission is a growing brigade of brilliant women scientists who are challenging stereotypes and pushing the boundaries of space exploration.",
    description:
      "From Chandrayaan to Gaganyaan, women engineers and physicists are increasingly taking lead roles, setting a new course for gender and STEM equality in India.",
    image:
      "https://cdn.theatlantic.com/thumbor/yKqzBPUABWfbouMpUCKSX6Qg7oE=/0x0:4000x2250/1952x1098/media/img/mt/2025/07/2025_06_BBBHouse/original.jpg",
  },
],

  latest: [
    {
      title: "Breaking: Modi Announces New AI Policy",
      subheading:
        "India aims to control its digital destiny with a framework focusing on ethical AI, local innovation, and global leadership.",
      description: "Modi's AI roadmap signals tech sovereignty push.",
      image:
        "https://images.unsplash.com/photo-1593789198777-f29bc259780e?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    },
    {
      title: "India Launches SpaceX-Style Rocket",
      subheading:
        "A landmark for India’s private aerospace sector, the launch reflects the government's effort to compete globally in space innovation.",
      description: "Private spaceflight reaches liftoff in India.",
      image:
        "https://cdn.theatlantic.com/thumbor/BCVBAJLrN_oZnewE0xj9n8-kWoc=/0x0:2160x2700/960x1200/media/img/2025/07/02/2025_07_02_Fireworks2_mpg/original.jpg",
    },
  ],
  mostRead: [
    {
      title: "The Rise of Indian Silicon Valley",
      subheading:
        "Bengaluru’s startup ecosystem is booming with VC investment, innovation hubs, and policy support. Could this surpass Silicon Valley?",
      description: "Bengaluru is becoming the tech capital of Asia.",
      image:
        "https://cdn.theatlantic.com/thumbor/BCVBAJLrN_oZnewE0xj9n8-kWoc=/0x0:2160x2700/960x1200/media/img/2025/07/02/2025_07_02_Fireworks2_mpg/original.jpg",
    },
    {
      title: "Inside Modi’s Vision for 2047",
      subheading:
        "India’s centennial will mark a powerful turning point if Modi’s long-term economic, social, and defense goals are achieved.",
      description: "India prepares for its next 100 years under vision 2047.",
      image:
        "https://images.unsplash.com/photo-1593789198777-f29bc259780e?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    },
  ],
};

export default data;
